fn read_manifest(path: &Path) -> anyhow::Result<BackupManifest> {
    let manifest_path = manifest_path(path);
    ensure_regular_file(&manifest_path, "backup manifest")?;
    let manifest = match fs::read_to_string(&manifest_path) {
        Ok(raw) => serde_json::from_str::<BackupManifest>(&raw)
            .with_context(|| format!("invalid backup manifest {}", manifest_path.display()))?,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            bail!(
                "backup manifest {} is missing; restore requires the database and manifest generated by `unionc backup`",
                manifest_path.display()
            )
        }
        Err(error) => return Err(error.into()),
    };
    Ok(manifest)
}

fn validate_manifest_bytes(manifest: &BackupManifest, database_sha256: &str) -> anyhow::Result<()> {
    if manifest.format_version != BACKUP_FORMAT_VERSION {
        bail!(
            "unsupported backup manifest format {}",
            manifest.format_version
        );
    }
    if manifest.database_sha256 != database_sha256 {
        bail!("backup SHA-256 does not match its manifest");
    }
    if manifest.application_version != env!("CARGO_PKG_VERSION") {
        bail!(
            "backup was created by application version {}; expected {}",
            manifest.application_version,
            env!("CARGO_PKG_VERSION")
        );
    }
    let expected_schema_version = super::current_schema_version();
    if manifest.schema_version != expected_schema_version {
        bail!(
            "backup manifest schema does not match the current schema: expected {}, found {}",
            expected_schema_version,
            manifest.schema_version
        );
    }
    Ok(())
}

fn build_manifest(
    database: &Path,
    database_sha256: String,
    schema_version: i64,
) -> anyhow::Result<BackupManifest> {
    Ok(BackupManifest {
        format_version: BACKUP_FORMAT_VERSION,
        application_version: env!("CARGO_PKG_VERSION").to_string(),
        created_at: chrono::Utc::now().to_rfc3339(),
        database_file: database
            .file_name()
            .and_then(|name| name.to_str())
            .context("backup output has no valid file name")?
            .to_string(),
        database_sha256,
        schema_version,
        encryption_key_id: crate::infra::secrets::current_key_id()?.to_string(),
    })
}

fn write_manifest(path: &Path, manifest: &BackupManifest) -> anyhow::Result<()> {
    ensure_new_output(path)?;
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)?;
    serde_json::to_writer_pretty(&mut file, manifest)?;
    file.write_all(b"\n")?;
    file.sync_all()?;
    Ok(())
}

fn manifest_path(database: &Path) -> PathBuf {
    let mut name: OsString = database.as_os_str().to_owned();
    name.push(".manifest.json");
    PathBuf::from(name)
}

fn ensure_new_output(path: &Path) -> anyhow::Result<()> {
    match fs::symlink_metadata(path) {
        Ok(_) => bail!("refusing to overwrite existing path {}", path.display()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => return Err(error.into()),
    }
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    if !parent.is_dir() {
        bail!(
            "output parent directory does not exist: {}",
            parent.display()
        );
    }
    Ok(())
}

fn ensure_regular_file(path: &Path, label: &str) -> anyhow::Result<()> {
    let metadata = fs::symlink_metadata(path)
        .with_context(|| format!("failed to inspect {label} {}", path.display()))?;
    if !metadata.file_type().is_file() {
        bail!("{label} is not a regular file: {}", path.display());
    }
    Ok(())
}

fn path_exists(path: &Path) -> anyhow::Result<bool> {
    match fs::symlink_metadata(path) {
        Ok(_) => Ok(true),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error.into()),
    }
}

fn absolute_path(path: &Path) -> anyhow::Result<PathBuf> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        Ok(std::env::current_dir()?.join(path))
    }
}

fn copy_private_file(source: &Path, target: &Path) -> anyhow::Result<()> {
    ensure_new_output(target)?;
    let mut input = File::open(source)?;
    let mut output = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(target)?;
    std::io::copy(&mut input, &mut output)?;
    output.sync_all()?;
    Ok(())
}

/// Copy a stopped SQLite database together with any WAL/SHM sidecars without
/// opening or mutating it. Every copied file is synced before this returns.
fn copy_database_family_private(source: &Path, target: &Path) -> anyhow::Result<()> {
    copy_private_file(source, target)?;
    for suffix in ["-wal", "-shm"] {
        let source_sidecar = database_sidecar(source, suffix);
        let metadata = match fs::symlink_metadata(&source_sidecar) {
            Ok(metadata) => metadata,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => continue,
            Err(error) => return Err(error.into()),
        };
        if !metadata.file_type().is_file() {
            bail!(
                "refusing unexpected SQLite sidecar type: {}",
                source_sidecar.display()
            );
        }
        copy_private_file(&source_sidecar, &database_sidecar(target, suffix))?;
    }
    Ok(())
}

fn sha256_file(path: &Path) -> anyhow::Result<String> {
    let mut file = File::open(path)?;
    let mut digest = Sha256::new();
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        digest.update(&buffer[..read]);
    }
    Ok(format!("{:x}", digest.finalize()))
}
